### PR TITLE
Yurbason gentx file

### PR DESCRIPTION
**Pull request by Yurbason**

### CODE REVIEW

**Review by kienvc — COMMENTED** [review]
Why did you leave 1 aura? It will be lost.

**Comment by Yurbason** [comment]
> Why did you leave 1 aura? It will be lost.

left 1 coin for transaction fees (voting, for example)

**Comment by kienvc** [comment]
> left 1 coin for transaction fees (voting, for example)

just bond all rewards as everyone, we will discuss about fees later

**Comment by Yurbason** [comment]
@kienvc 
reloaded the file

**Pull request merged**
