### PR TITLE
Add gentx ramuchi.tech

### PR DESCRIPTION
**Pull request by ramuchi**

### CODE REVIEW

**Review by kienvc — COMMENTED** [review]
1aura will be lost.

**Comment by ramuchi** [comment]
Need 7500 exactly? what about the commission costs?

**Comment by kienvc** [comment]
it charges delegators, not validator.

**Comment by ramuchi** [comment]
--fees = 0? 
Will I be able to get rewards from the validator? and delegate them to my validator again when inflation is enabled?

**Comment by kienvc** [comment]
make sure you will, let bond all of your rewards first and we can discuss how to withdraw it later

**Pull request closed without merging**
