### PR TITLE
Create gentx-darvin.json

### PR DESCRIPTION
**Pull request by Danil00524**

### CODE REVIEW

**Review by kienvc — COMMENTED** [review]
please check your chain-id setting.

**Comment by Danil00524** [comment]
> please check your chain-id setting.

updated

**Comment by kienvc** [comment]
amount of your bonded token

**Comment by Danil00524** [comment]
I used this guide - https://github.com/aura-nw/mainnet-artifacts/blob/main/xstaxy-1/genesis-validators-guide.md
What's wrong?

**Comment by kienvc** [comment]
you should have 7500 bonded aura

**Comment by Danil00524** [comment]
> you should have 7500 bonded aura

done

**Pull request merged**
