### PR TITLE
Update Yurbason-pledger.md

### PR DESCRIPTION
**Pull request by Yurbason**

### CODE REVIEW

**Comment by kienvc** [comment]
Please edit your commission between 3% and 5%

**Comment by Yurbason** [comment]
> Please edit your commission between 3% and 5%

изображение_2023-07-04_105616534
I always had this commission from the very beginning

**Comment by CrazySerGo** [comment]
@Yurbason it's in your pledge.
4. Commission rate is greater than 0% and smaller or equal to 8%

**Comment by Yurbason** [comment]
> @Yurbason it's in your pledge. 4. Commission rate is greater than 0% and smaller or equal to 8%

omg ok thnx
changed :)

**Pull request merged**
