### PR TITLE
Update popsteam-pledger.md

### PR DESCRIPTION
**Pull request by pops-one**
Updated our Testnet Validator address which was wrong.

### CODE REVIEW

**Comment by kienvc** [comment]
Please update your commission between 3% to 5%

**Comment by pops-one** [comment]
> Please update your commission between 3% to 5%

Hello, we thought 5% was still ok. So should we go lower than that? Would 4% be ok. This is our validator on mainnet: https://aurascan.io/validators/auravaloper1hmmlyt7mchy6t49z0hmacsem3pyljpzhv9leat

**Comment by kienvc** [comment]
Nah, I mean update your pledge file in PR

**Comment by yelllowsin** [comment]
> Nah, I mean update your pledge file in PR

Ah got it. Fixed it with the commit above. I think you can merge de PR now.

**Comment by pops-one** [comment]
> Nah, I mean update your pledge file in PR

Ah got it. Fixed it with the commit above. I think you can merge de PR now.

**Pull request merged**
