### PR TITLE
Updated pledge

### PR DESCRIPTION
**Pull request by effofxprime**
In the event we don't need to update the pledge, do we still need to submit a PR for it?  Just a question for the future.

### CODE REVIEW

**Comment by kienvc** [comment]
if nothing change, then you don't need  to submit PR

**Comment by kienvc** [comment]
Could you edit commission between 3% to 5%

**Comment by effofxprime** [comment]
It is in that range, it's 5%. Or do you mean in the PR?

**Comment by kienvc** [comment]
sorry, I mean in the PR

**Comment by effofxprime** [comment]
Updated the commission part.

**Pull request merged**
